openapi: 3.0.0
servers:
  - description: SS12000
    url: "https://virtserver.swaggerhub.com/TK450-AG10/SS12000/1.0.0"
info:
  description: |
    This is a test implementation of SS12000 v2
    [TK450](https://www.sis.se/standardutveckling/tksidor/tk400499/sistk450/)
  version: 2.0.0
  title: SS12000
  termsOfService: "https://www.sis.se/standardutveckling/tksidor/tk400499/sistk450/"
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: person
    description: Operations about person
paths:
  /person:
    post:
      tags:
        - person
      summary: Create person
      description: This can only be done by the logged in person.
      operationId: createPerson
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "schemas.yaml#/Person"
        description: Created person object
        required: true
  /persons/id/{id}:
    get:
      tags:
        - person
      summary: Get persons
      operationId: getPersonsById
      parameters:
        - name: id
          in: path
          description: En eller flera idn på personer
          required: true
          schema:
            type: array
            items:
              type: string
              format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/Person"
            application/xml:
              schema:
                $ref: "schemas.yaml#/Person"
        "400":
          description: Invalid personname supplied
        "404":
          description: Person not found
  /persons/pnr/{pnr}:
    get:
      tags:
        - person
      summary: Get persons
      operationId: getPersonsByPno
      parameters:
        - name: pnr
          in: path
          description: Ett eller flera personnummer att söka efter
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/Person"
            application/xml:
              schema:
                $ref: "schemas.yaml#/Person"
        "400":
          description: Invalid personname supplied
        "404":
          description: Person not found
  /persons/principal/{principal}:
    get:
      tags:
        - person
      summary: Get persons
      operationId: getPersonsByPrincipal
      parameters:
        - name: principal
          in: path
          description: Principaler att söka på
          required: true
          schema:
            type: array
            items:
              type: string
              format: email
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/Person"
            application/xml:
              schema:
                $ref: "schemas.yaml#/Person"
        "400":
          description: Invalid personname supplied
        "404":
          description: Person not found
  "/person/{id}":
    get:
      tags:
        - person
      summary: Get person by person name
      operationId: getPersonByName
      parameters:
        - name: id
          in: path
          description: a list of ids for the persons to fetch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/Person"
            application/xml:
              schema:
                $ref: "schemas.yaml#/Person"
        "400":
          description: Invalid personname supplied
        "404":
          description: Person not found
    delete:
      tags:
        - person
      summary: Delete person
      description: This can only be done by the logged in person.
      operationId: deletePerson
      parameters:
        - name: id
          in: path
          description: The person that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        "400":
          description: Invalid personname supplied
        "404":
          description: Person not found
externalDocs:
  description: Find out more about Swagger
  url: "http://swagger.io"
components:
  schemas:
    $ref: "schemas.yaml"
  parameters:
    FilterParam:
      in: query
      name: filter
      required: false
      schema:
        type: string
      description: >-
        Filters according to
        [RFC7644](https://tools.ietf.org/html/rfc7644#section-3.4.2.2).
